### ISSUE TITLE
Error 127 during make

### ISSUE THREAD

**Issue by buteomont** [jimstudt/ook-decoder#9]
When I enter _make_ per the instructions:

`~/apps/ook-decoder$ make

cc -std=c99  -Wall -Werror -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -D_DARWIN_C_SOURCE=1 -pg -g -O0 -pg  -ffast-math -O3 -MMD   -c -o ookd.o ookd.c
cc -std=c99  -Wall -Werror -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -D_DARWIN_C_SOURCE=1 -pg -g -O0 -pg  -ffast-math -O3 -MMD   -c -o rtl.o rtl.c
cc -std=c99  -Wall -Werror -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -D_DARWIN_C_SOURCE=1 -pg -g -O0 -pg  -ffast-math -O3 -MMD   -c -o ook.o ook.c
cc -std=c99  -Wall -Werror -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -D_DARWIN_C_SOURCE=1 -pg -g -O0 -pg  -ffast-math -O3 -MMD    ookd.o rtl.o ook.o  -lrtlsdr -lm -o ookd
cc -std=c99  -Wall -Werror -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -D_DARWIN_C_SOURCE=1 -pg -g -O0 -pg  -ffast-math -O3 -MMD   -c -o ookdump.o ookdump.c
cc -std=c99  -Wall -Werror -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -D_DARWIN_C_SOURCE=1 -pg -g -O0 -pg  -ffast-math -O3 -MMD    ookdump.o ook.o  -lm -o ookdump
cc -std=c99  -Wall -Werror -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -D_DARWIN_C_SOURCE=1 -pg -g -O0 -pg  -ffast-math -O3 -MMD   -c -o wh1080.o wh1080.c
cc -std=c99  -Wall -Werror -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -D_DARWIN_C_SOURCE=1 -pg -g -O0 -pg  -ffast-math -O3 -MMD    wh1080.o ook.o  -lm -o wh1080
cc -std=c99  -Wall -Werror -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -D_DARWIN_C_SOURCE=1 -pg -g -O0 -pg  -ffast-math -O3 -MMD   -c -o oregonsci.o oregonsci.c
cc -std=c99  -Wall -Werror -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -D_DARWIN_C_SOURCE=1 -pg -g -O0 -pg  -ffast-math -O3 -MMD   -c -o datum.o datum.c
cc -std=c99  -Wall -Werror -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -D_DARWIN_C_SOURCE=1 -pg -g -O0 -pg  -ffast-math -O3 -MMD    oregonsci.o ook.o datum.o  -lm -o oregonsci
cc -std=c99  -Wall -Werror -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -D_DARWIN_C_SOURCE=1 -pg -g -O0 -pg  -ffast-math -O3 -MMD   -c -o ws2300.o ws2300.c
cc -std=c99  -Wall -Werror -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -D_DARWIN_C_SOURCE=1 -pg -g -O0 -pg  -ffast-math -O3 -MMD    ws2300.o ook.o  -lm -o ws2300
cc -std=c99  -Wall -Werror -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -D_DARWIN_C_SOURCE=1 -pg -g -O0 -pg  -ffast-math -O3 -MMD   -c -o nexa.o nexa.c
cc -std=c99  -Wall -Werror -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -D_DARWIN_C_SOURCE=1 -pg -g -O0 -pg  -ffast-math -O3 -MMD    nexa.o ook.o  -lm -o nexa
cc -std=c99  -Wall -Werror -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -D_DARWIN_C_SOURCE=1 -pg -g -O0 -pg  -ffast-math -O3 -MMD   -c -o acurite.o acurite.c
cc -std=c99  -Wall -Werror -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE=1 -D_DEFAULT_SOURCE=1 -D_DARWIN_C_SOURCE=1 -pg -g -O0 -pg  -ffast-math -O3 -MMD    acurite.o ook.o  -lm -o acurite
( cd go ; GOPATH=`pwd` go install ooklog )
/bin/sh: 1: go: not found
make: *** [Makefile:47: go/bin/ooklog] Error 127`

The README file also states that this is alpha code and is on hold.  Is this the cause of my failure?
Thanks, David

**Comment by jimstudt** [comment]
It looks like you don't have a `go` compiler installed. Some of the tools are written in `go`.

**Comment by buteomont** [comment]
Does it require a particular version?  I installed the go compiler per https://go.dev/doc/install and now get this error: 
```
make
( cd go ; GOPATH=`pwd` go install ooklog )
go: 'go install' requires a version when current directory is not in a module
	Try 'go install ooklog@latest' to install the latest version
make: *** [Makefile:47: go/bin/ooklog] Error 1
```

I modified the Makefile to include the "@latest" bit and then got this error:
```
make
( cd go ; GOPATH=`pwd` go install ooklog@latest )
go: ooklog@latest: malformed module path "ooklog": missing dot in first path element
make: *** [Makefile:47: go/bin/ooklog] Error 1
```
I don't know squat about go (never heard of it before now), but I would really like to try this software!
